/**
 * Production-grade tests for the built web app's security posture and artifact integrity.
 *
 * These tests run against the built `dist/` output (generated by `npm run build`).
 * They verify:
 * - CSP meta tag is present and correctly configured
 * - No polyfill cruft remains in index.html
 * - The foliate-js fork patches are present in the built node_modules
 * - PDF.js fixes are present in the built output
 */

import { describe, it, expect, beforeAll } from 'vitest';
import { readFileSync, existsSync, readdirSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.resolve(__dirname, '../../..');
const DIST_DIR = path.join(PROJECT_ROOT, 'dist');
const ELECTRON_APP_DIR = path.join(PROJECT_ROOT, 'electron/app');

// Only run these tests if the dist exists (build has been run)
const DIST_EXISTS = existsSync(DIST_DIR);
const ELECTRON_APP_EXISTS = existsSync(ELECTRON_APP_DIR);

const describeIf = (condition: boolean) => (condition ? describe : describe.skip);

// ---------------------------------------------------------------------------
// CSP Security Tests
// ---------------------------------------------------------------------------

/**
 * Parse a CSP string into an object keyed by directive name.
 * Handles unescaped single quotes and semicolons within directive values.
 */
function parseCSP(csp: string): Record<string, string> {
  const result: Record<string, string> = {};
  let i = 0;
  let current = '';

  const advancePastSpace = () => { while (i < csp.length && csp[i] === ' ') i++; };

  while (i < csp.length) {
    // Skip leading spaces
    advancePastSpace();
    if (i >= csp.length) break;

    // Read directive name (up to first space)
    let dirEnd = i;
    while (dirEnd < csp.length && csp[dirEnd] !== ' ' && csp[dirEnd] !== ';') dirEnd++;
    const directive = csp.slice(i, dirEnd);
    i = dirEnd;
    advancePastSpace();

    // Read directive value (up to next semicolon or end)
    let valEnd = i;
    while (valEnd < csp.length && csp[valEnd] !== ';') valEnd++;
    const value = csp.slice(i, valEnd).trim();
    if (directive) result[directive] = value;

    i = valEnd + 1;
  }

  return result;
}

describeIf(DIST_EXISTS)('index.html CSP configuration', () => {
  // The CSP in the source index.html is set by the dev/build process.
  // It restricts inline scripts and external sources appropriately.
  const indexHtml = readFileSync(path.join(DIST_DIR, 'index.html'), 'utf-8');

  it('has a CSP meta tag', () => {
    expect(indexHtml).toMatch(/<meta[^>]+http-equiv=["']Content-Security-Policy["']/i);
  });

  it('CSP includes blob: for PDF workers and EPUB content', () => {
    // blob: is required for PDF.js worker communication and EPUB content blobs
    expect(indexHtml).toContain('blob:');
  });

  it('CSP restricts script-src to self (no unsafe-eval in production)', () => {
    // Production builds should not allow 'unsafe-eval'
    expect(indexHtml).not.toMatch(/script-src[^;]*'unsafe-eval'/);
  });

  it('CSP includes Google Fonts domains for styled reading', () => {
    expect(indexHtml).toContain('fonts.googleapis.com');
    expect(indexHtml).toContain('fonts.gstatic.com');
  });

  it('CSP has connect-src restricted to self and blob', () => {
    // connect-src should not allow arbitrary external connections
    expect(indexHtml).toMatch(/connect-src\s+['"][^'"]*self[^'"]*['"]/);
  });

  it('CSP does not allow data: in script-src (no inline script execution via data:)', () => {
    // data: in script-src would allow <script src="data:..."> which is dangerous
    const csp = indexHtml.match(/script-src\s+([^;]+)/);
    if (csp) {
      expect(csp[1]).not.toContain('data:');
    }
  });
});

describeIf(ELECTRON_APP_EXISTS)('electron/app CSP (runtime-injected by setup.ts)', () => {
  // The electron/app/index.html CSP is injected at runtime by electron/src/setup.ts.
  // We test that the setup code exists and produces correct CSP headers.
  const electronAppHtml = readFileSync(path.join(ELECTRON_APP_DIR, 'index.html'), 'utf-8');

  it('has a CSP meta tag', () => {
    expect(electronAppHtml).toMatch(/<meta[^>]+http-equiv=["']Content-Security-Policy["']/i);
  });

  it('CSP includes blob: for PDF workers', () => {
    expect(electronAppHtml).toContain('blob:');
  });

  it('CSP does not allow unsafe-eval in production Electron', () => {
    // Production Electron (not dev) should not have unsafe-eval
    // The dev mode CSP includes unsafe-eval but production should not
    expect(electronAppHtml).not.toMatch(/script-src[^;]*'unsafe-eval'/);
  });
});

// ---------------------------------------------------------------------------
// index.html cleanliness — no polyfill cruft
// ---------------------------------------------------------------------------

describeIf(DIST_EXISTS)('index.html is clean (no debug/hack artifacts)', () => {
  const indexHtml = readFileSync(path.join(DIST_DIR, 'index.html'), 'utf-8');

  it('has no Polyfills running console.log debug statement', () => {
    expect(indexHtml).not.toContain('Polyfills running');
    expect(indexHtml).not.toContain('Polyfills done');
  });

  it('has no toHex polyfill inline script', () => {
    expect(indexHtml).not.toContain('Uint8Array.prototype.toHex');
    expect(indexHtml).not.toContain('toHex exists');
  });

  it('has no ES2024 polyfill for Object.groupBy', () => {
    // We removed these; they should not be in the built HTML
    expect(indexHtml).not.toContain('Object.groupBy');
    expect(indexHtml).not.toContain('Map.groupBy');
  });

  it('has no Promise.withResolvers polyfill', () => {
    expect(indexHtml).not.toContain('Promise.withResolvers');
    expect(indexHtml).not.toContain('Promise.try');
  });

  it('has no monkey-patch of getDocument', () => {
    // The monkey-patch was removed from pdfParser.ts
    expect(indexHtml).not.toContain('getOrInsertComputed');
    // getOrInsertComputed should only be in pdf.mjs via the Rollup patch
  });

  it('has no console.log statements in the body', () => {
    // Extract body content and check for debug logs
    const bodyMatch = indexHtml.match(/<body>([\s\S]*)<\/body>/i);
    if (bodyMatch) {
      const body = bodyMatch[1];
      expect(body).not.toMatch(/console\.log/);
    }
  });

  it('has a #root div', () => {
    expect(indexHtml).toContain('id="root"');
  });

  it('has a script type="module" entry point', () => {
    // Vite hashes the output to /assets/index-HASH.js — check for the pattern
    expect(indexHtml).toContain('type="module"');
    expect(indexHtml).toMatch(/\/assets\/index-[A-Za-z0-9_-]+\.js/);
  });
});

// ---------------------------------------------------------------------------
// pdfParser.ts — no monkey-patch, proper String() coercion
// ---------------------------------------------------------------------------

describeIf(DIST_EXISTS)('pdfParser.ts source is clean', () => {
  const pdfParser = readFileSync(path.join(PROJECT_ROOT, 'src/parsers/pdfParser.ts'), 'utf-8');

  it('has no monkey-patch of getDocument', () => {
    expect(pdfParser).not.toContain('getOrInsertComputed');
    expect(pdfParser).not.toContain('_origGetDocument');
    expect(pdfParser).not.toContain('Monkey-patch');
  });

  it('has String() coercion for rawTitle', () => {
    // The fix: String(rawTitle) to handle array/object metadata values
    expect(pdfParser).toContain('String(rawTitle)');
  });

  it('has String() coercion for rawAuthor', () => {
    expect(pdfParser).toContain('String(rawAuthor)');
  });

  it('has String() coercion for rawDescription', () => {
    expect(pdfParser).toContain('String(rawDescription)');
  });

  it('has nullish coalescing for language and publisher', () => {
    // language = metadata?.get('dc:language') != null ? String(...) : undefined
    expect(pdfParser).toContain('!= null');
    expect(pdfParser).toContain('String(metadata');
  });

  it('imports pdfjsLib from foliate-js directly', () => {
    expect(pdfParser).toContain("import { pdfjsLib } from 'foliate-js/pdfjs.js'");
    expect(pdfParser).not.toContain('pdfjsLib as any).getDocument = function');
  });
});

// ---------------------------------------------------------------------------
// foliate-js fork patches in node_modules
// ---------------------------------------------------------------------------

describe('foliate-js fork patches', () => {
  const nodeModulesPdfMjs = path.join(
    PROJECT_ROOT, 'node_modules/foliate-js/vendor/pdfjs/pdf.mjs'
  );
  const nodeModulesPdfWorkerMjs = path.join(
    PROJECT_ROOT, 'node_modules/foliate-js/vendor/pdfjs/pdf.worker.mjs'
  );

  it('pdf.mjs has the OffReader patch header', () => {
    const content = readFileSync(nodeModulesPdfMjs, 'utf-8');
    expect(content).toContain('// -- OffReader patch:');
    expect(content).toContain('bytesToHex');
    expect(content).toContain('bytesToBase64');
    expect(content).toContain('base64ToBytes');
    expect(content).toContain('getOrInsertComputed');
  });

  it('pdf.worker.mjs has the OffReader patch header', () => {
    const content = readFileSync(nodeModulesPdfWorkerMjs, 'utf-8');
    expect(content).toContain('// -- OffReader patch:');
    expect(content).toContain('bytesToHex');
    expect(content).toContain('getOrInsertComputed');
  });

  it('pdf.mjs has no stale .toBase64() calls', () => {
    const content = readFileSync(nodeModulesPdfMjs, 'utf-8');
    expect(content).not.toContain('.toBase64()');
  });

  it('pdf.worker.mjs has no stale .toHex() calls', () => {
    const content = readFileSync(nodeModulesPdfWorkerMjs, 'utf-8');
    expect(content).not.toContain('.toHex()');
  });

  it('pdf.worker.mjs has no stale Uint8Array.fromBase64 calls', () => {
    const content = readFileSync(nodeModulesPdfWorkerMjs, 'utf-8');
    expect(content).not.toContain('Uint8Array.fromBase64(this[$content])');
  });
});

// ---------------------------------------------------------------------------
// getAnchorUrl fix in pdf.js
// ---------------------------------------------------------------------------

describe('getAnchorUrl stub in pdf.js', () => {
  const pdfJsPath = path.join(PROJECT_ROOT, 'node_modules/foliate-js/pdf.js');

  it('pdf.js exists in foliate-js', () => {
    expect(existsSync(pdfJsPath)).toBe(true);
  });

  it('pdf.js defines a linkService with getAnchorUrl', () => {
    const content = readFileSync(pdfJsPath, 'utf-8');
    expect(content).toContain('getAnchorUrl');
  });

  it('getAnchorUrl returns the hash (not undefined)', () => {
    const content = readFileSync(pdfJsPath, 'utf-8');
    // getAnchorUrl: hash => hash (returns the argument directly)
    expect(content).toMatch(/getAnchorUrl:\s*\w+\s*=>\s*\w+/);
  });
});

// ---------------------------------------------------------------------------
// Built dist assets
// ---------------------------------------------------------------------------

describeIf(DIST_EXISTS)('dist directory structure', () => {
  it('dist/index.html exists', () => {
    expect(existsSync(path.join(DIST_DIR, 'index.html'))).toBe(true);
  });

  it('dist/assets directory exists with JS chunks', () => {
    const assetsDir = path.join(DIST_DIR, 'assets');
    expect(existsSync(assetsDir)).toBe(true);
    const files = readdirSync(assetsDir).filter(f => f.endsWith('.js'));
    expect(files.length).toBeGreaterThan(0);
  });

  it('dist/assets has a PDF worker file', () => {
    const assetsDir = path.join(DIST_DIR, 'assets');
    const files = readdirSync(assetsDir);
    const workerFiles = files.filter(f => f.includes('pdf.worker'));
    expect(workerFiles.length).toBeGreaterThan(0);
    expect(workerFiles[0]).toMatch(/\.mjs$/);
  });

  it('main bundle starts with OffReader patch header in pdf.mjs', () => {
    const assetsDir = path.join(DIST_DIR, 'assets');
    const files = readdirSync(assetsDir);
    const pdfWorkerFile = files.find(f => f.includes('pdf.worker') && f.endsWith('.mjs'));
    expect(pdfWorkerFile).toBeTruthy();
    const content = readFileSync(path.join(assetsDir, pdfWorkerFile!), 'utf-8');
    expect(content).toContain('// -- OffReader patch:');
    expect(content).toContain('bytesToHex');
  });
});

// ---------------------------------------------------------------------------
// electron/app assets (the packaged electron app)
// ---------------------------------------------------------------------------

describeIf(ELECTRON_APP_EXISTS)('electron/app directory structure', () => {
  it('electron/app/index.html exists', () => {
    expect(existsSync(path.join(ELECTRON_APP_DIR, 'index.html'))).toBe(true);
  });

  it('electron/app/assets has JS bundles', () => {
    const assetsDir = path.join(ELECTRON_APP_DIR, 'assets');
    expect(existsSync(assetsDir)).toBe(true);
    const files = readdirSync(assetsDir).filter(f => f.endsWith('.js'));
    expect(files.length).toBeGreaterThan(0);
  });

  it('electron/app/assets has a PDF worker .mjs file', () => {
    const assetsDir = path.join(ELECTRON_APP_DIR, 'assets');
    const files = readdirSync(assetsDir);
    const workerFiles = files.filter(f => f.includes('pdf.worker') && f.endsWith('.mjs'));
    expect(workerFiles.length).toBeGreaterThan(0);
  });

  it('electron/app/assets has the OffReader patch in pdf.worker.mjs', () => {
    const assetsDir = path.join(ELECTRON_APP_DIR, 'assets');
    const files = readdirSync(assetsDir);
    const workerFile = files.find(f => f.includes('pdf.worker') && f.endsWith('.mjs'));
    expect(workerFile).toBeTruthy();
    const content = readFileSync(path.join(assetsDir, workerFile!), 'utf-8');
    expect(content).toContain('// -- OffReader patch:');
  });
});
